# Netlify configuration — SSIAP Training
# ⚠️ IMPORTANT : supprimer index.html de la racine pour que ces redirections fonctionnent

[[redirects]]
  from = "/"
  to = "/center/center-login.html"
  status = 302

[[redirects]]
  from = "/center"
  to = "/center/center-login.html"
  status = 302

[[redirects]]
  from = "/formateur"
  to = "/formateur/formateur-login.html"
  status = 302

[[redirects]]
  from = "/stagiaire"
  to = "/stagiaire/stagiaire-login.html"
  status = 302

[[redirects]]
  from = "/admin"
  to = "/admin/admin-login.html"
  status = 302

[[redirects]]
  from = "/admin/"
  to = "/admin/admin-login.html"
  status = 302